export enum ExpirationEnum {
    ACCESS_TOKEN_EXPIRATION = "30m",
    REFRESH_TOKEN_EXPIRATION = "30d",
    SESSION_DEFAULT_EXPIRATION = 7 * 24 * 60 * 60,
    VERIFICATION_CODE_DEFAULT_EXPIRATION = 5 * 60,
    DEVICE_EXPIRATION = 5 * 60,
    DEFAULT_CACHE_EXPIRATION = 60 * 60 * 1000,
}