version: '3.3'

services:
  postgres: 
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data'
    networks:
      - default
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5436:5432

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - default
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redis_data:
